### ISSUE TITLE
npm install fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by marxanweb** [marxanweb/marxan-client#35]
This used to work but no longer does. A known issue on Ubuntu https://github.com/npm/cli/issues/681

![Screen Shot 2020-03-27 at 16 24 41](https://user-images.githubusercontent.com/62133576/77771932-a1eeeb80-7047-11ea-8a9f-6fd14daa58f5.png)

**Comment by marxanweb** [comment]
Update to the latest version of node and npm:

apt -y install nodejs make gcc g++
sudo apt -y install nodejs make gcc g++
Now
a_cottam@instance-1:~/marxan-client$ nodejs -v
v10.19.0
a_cottam@instance-1:~/marxan-client$ npm -v
6.13.4

**Comment by tibistibi** [comment]
i think the first line is wrong (as it is almost the same as the second):

```
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -  
apt -y install nodejs make gcc g++
```

And i wonder if:
`     sudo npm install -g npm` 
also would work

**Comment by andrewcottam** [comment]
Thanks a lot - yes indeed it is wrong. I'll edit it and try the install again.
