### ISSUE TITLE
`MapError: The layer 'marxan_pu_results_layer' does not exist in the map's style and cannot be styled.`

### ISSUE THREAD

**Issue by carlostighe** [marxanweb/marxan-client#36]
Hey Andrew, 
Its me again..... 
I pulled down the most recent code this week and am now running into the following error....
`MapError: The layer 'marxan_pu_results_layer' does not exist in the map's style and cannot be styled.`

Im looking into it myself but wondering if you have come across it?

Im running my own server locally, have uploaded my own pu layer, own features, and marxan runs but then at the end of the run this error pops up.

**Comment by andrewcottam** [comment]
Wow! You've done well to get it running locally.

This means that the layer from Mapbox that is used to render the planning grids cannot be found and the most likely explanation is that something happened during the upload to Mapbox when you imported the planning grid. Only yesterday I added in error handling on uploading to Mapbox because errors were not being caught, so you should see Mapbox errors if you are using commits from fa530e4c5bf57d16ea99479b8661ccf38ae54fa6 onwards.

**Comment by carlostighe** [comment]
Okay so I probably need to re upload my pu layer. 
Im running on linux and dont use anaconda so ended up dockerising and using docker-compose. 
It works reasonably well but is time consuming when there are changes and Im having trouble persisting the database sometimes. 

I will at some stage do a pull request to add the docker files to your repos.

**Comment by carlostighe** [comment]
Unfortunately re-uploading the pu layer didnt do the job. Ill keep looking into it

**Comment by andrewcottam** [comment]
Looks like its still loading in Mapbox - you can double check if it is your planning grid by hovering over the name in the planning grid window to see if it is pu_e5dfa4f850e54a01a7fda0aec7401:

![Screen Shot 2020-07-02 at 17 44 25](https://user-images.githubusercontent.com/596494/86379921-c502ea00-bc8b-11ea-9f2e-2e4f6e25b3f9.png)

**Comment by andrewcottam** [comment]
I've not looked into Docker yet (on my list of things to do!) but that would be amazing if we could containerize it. I've had issues with installing on a Mac - would containerizing it solve that problem?

**Comment by carlostighe** [comment]
Yes it should solve those issues.

**Comment by carlostighe** [comment]
That does not seem to be my planning layer. 

![marxanweb](https://user-images.githubusercontent.com/4867797/86381726-70f50700-bc85-11ea-8fb4-5383c1c1f221.png)

**Comment by andrewcottam** [comment]
Oh OK - if it's showing the grid then there isn't an issue with Mapbox - it must be something else. I have seen that error before, but it was a while back and my memory fades :) - I'll try to dig back and see what I can find. Also, you could have a look in the Console to see if there are any exceptions there.

**Comment by carlostighe** [comment]
It doesnt seem to be running any of the projects. Tried both British one and starter project and same error.

**Comment by andrewcottam** [comment]
The results layer is added [here](https://github.com/marxanweb/marxan-client/blob/c6c00244528684c885d2a337ca4984bb0cdecbe4/src/App.js#L2242). If you are comfortable debugging in Chrome you could try putting a breakpoint in on that line and seeing why it is not being added.

**Comment by carlostighe** [comment]
Andrew,
Ill give that a look. 
Id love to skype but maybe next week? Just finishing up for the day now.

**Comment by andrewcottam** [comment]
Tomorrow afternoon would be great - i'll look you up on skype

**Comment by carlostighe** [comment]
Great. Chat then - live:carlostighe

**Comment by carlostighe** [comment]
Okay so I was looking into this a bit further and it seems (changePlanningGrid())[https://github.com/marxanweb/marxan-client/blob/c6c00244528684c885d2a337ca4984bb0cdecbe4/src/App.js#L2195] isnt being triggered.

**Comment by andrewcottam** [comment]
Glad you sorted it!
