### ISSUE TITLE
Turn off login 

### ISSUE THREAD

**Issue by carlostighe** [marxanweb/marxan-client#40]
Hi Andrew,

Do you have anyway to turn off login screen, for development, so I dont have to login everytime on server reload?

**Comment by andrewcottam** [comment]
Unfortunately not - I did have until later versions. Can't remember why I
got rid of it. However, you should be able to avoid the login screen by
passing in parameters for the server, user and project, eg.

https://app.marxanweb.org/?server=Microsoft Azure Trial
&user=admin&project=Start project

This will load the project directly (as read only).
